name: Build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Zip jenv taxonomy
      run: zip -r jenv_taxonomy_2022.zip ./jenv_taxonomy_2022
    - name: Zip rj taxonomy
      run: zip -r rj_taxonomy_2022.zip ./rj_taxonomy_2022
    - uses: actions/setup-python@v4 
      with:
        python-version: 'pypy3.9' 
    - run: pip install arelle-release
    - uses: actions/upload-artifact@v3
      with:
        name: taxonomy-packages
        path: |
          ${{ github.workspace }}/jenv_taxonomy_2022.zip
          ${{ github.workspace }}/rj_taxonomy_2022.zip
