name: Build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Zip Folder
      run: zip -r jenv_taxonomy_2022.zip ./jenv_taxonomy_2022
    - uses: actions/upload-artifact@v3
      with:
        name: jenv_taxonomy_2022
        path: ${{ github.workspace }}/jenv_taxonomy_2022.zip
