name: Build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: vimtor/action-zip@v1
      with:
        files: ./jenv_taxonomy_2022
        dest: jenv_taxonomy_2022.zip
    - uses: vimtor/action-zip@v1
      with:
        files: ./rj_taxonomy_2022
        dest: rj_taxonomy_2022.zip
    - run: "dir"
    - run: './script/arelle/arelleCmdline.exe --packages ".\rj_taxonomy_2022.zip|.\jenv_taxonomy_2022.zip" -f https://www.rjnet.nl/taxonomy/2023-06-30/rj_cor.xsd -v'
    - uses: actions/upload-artifact@v3
      with:
        name: taxonomy-packages
        path: |
          ${{ github.workspace }}/jenv_taxonomy_2022.zip
          ${{ github.workspace }}/rj_taxonomy_2022.zip
