name: Build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: vimtor/action-zip@v1
      with:
        files: jenv_taxonomy_2022/
        recursive: false
        dest: jenv_taxonomy_2022.zip
    - uses: vimtor/action-zip@v1
      with:
        files: rj_taxonomy_2022/
        recursive: false
        dest: rj_taxonomy_2022.zip
    - run: './script/arelle/arelleCmdline.exe --packages ".\rj_taxonomy_2022.zip|.\jenv_taxonomy_2022.zip" -f https://www.rjnet.nl/taxonomy/2023-06-30/rj_cor.xsd -v --logFile arelle-log.xml'
    - name: Get level from output
      id: get_level
      shell: pwsh  
      run: |
        $arellelog = get-childitem -Filter arelle-log.xml -Recurse | Sort-Object -Descending -Property LastWriteTime -Top 1
        Write-Output $arellelog.FullName
        [xml]$arellelog = Get-Content -Path $arellelog.FullName
        $level = $arellelog.log.entry.'level'
        Write-Output "name=level::$level" >> $GITHUB_OUTPUT
    - name: Check coverage tolerance
      if: ${{ steps.get_level.outputs.level == 'error' }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('Error(s) present')
    - uses: actions/upload-artifact@v3
      with:
        name: taxonomy-packages
        path: |
          ${{ github.workspace }}/jenv_taxonomy_2022.zip
          ${{ github.workspace }}/rj_taxonomy_2022.zip
          ${{ github.workspace }}/nen_taxonomy_2022.zip
          ${{ github.workspace }}/iso_taxonomy_2022.zip
